### ISSUE TITLE
Wrong floating-label placement with prefix usage

### ISSUE THREAD

**Issue by vinerz** [PolymerElements/paper-input#228]
Hello everyone! I have a `readonly` `prefixed` and `prefilled` paper-input, with this markup:

```html
<paper-input name="username" id="username" label="Usuário" value="{{account.username}}" readonly always-float-label>
    <div prefix>http://example.com/</div>
</paper-input>
```

When the page renders, I get this result:
![Issue](https://sc-cdn.scaleengine.net/i/471716519dc857795ea792ce2d1ccf141.png)

Look at the floating-label misplaced after the prefix area!

When I give the paper-input focus, it fixes itself:
![Issue - Focused](https://sc-cdn.scaleengine.net/i/cb02560f9fe4d20669f9d7252a882ce3.png)

What can I do?

Thanks in advance,
Vinicius

**Comment by notwaldorf** [comment]
What version of `paper-input` are you using? This should have been fixed in v1.0.18

**Comment by vinerz** [comment]
Hello @notwaldorf! I've updated to the latest version 1.0.18, but the issue persists.

**Comment by notwaldorf** [comment]
Ah, I can repro it. Thanks!

**Comment by vinerz** [comment]
@notwaldorf, thanks for the answer, but the latest version of paper-input (1.1.0) still have this issue.

**Comment by notwaldorf** [comment]
@vinerz Gah! I even have a test for this and I still missed an edge case. 😓

**Comment by notwaldorf** [comment]
Oh, that's because the fix is in master and has not been released. It should be fixed in 1.1.1

**Comment by vinerz** [comment]
@notwaldorf, just to confirm that this issue is fixed now. Thank you for your attention.

**Comment by notwaldorf** [comment]
Whew! Good to hear :)
